server:
  port: 9003 # 服务的端口
spring:
  application:
    name: hrm-fastdfs # 应用的名字
eureka:
  client: # 这个服务是eureka的客户端
    service-url: # eureka服务端的url
      defaultZone: http://localhost:7001/eureka # 注册到eureka服务端，服务端的地址
  instance:
    prefer-ip-address: true # 显示ip地址